/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jlibfprint_JlibFprint_fp_print_data_type */

#ifndef _Included_jlibfprint_JlibFprint_fp_print_data_type
#define _Included_jlibfprint_JlibFprint_fp_print_data_type
#ifdef __cplusplus
extern "C" {
#endif
#undef jlibfprint_JlibFprint_fp_print_data_type_PRINT_DATA_RAW
#define jlibfprint_JlibFprint_fp_print_data_type_PRINT_DATA_RAW 0L
#undef jlibfprint_JlibFprint_fp_print_data_type_PRINT_DATA_NBIS_MINUTIAE
#define jlibfprint_JlibFprint_fp_print_data_type_PRINT_DATA_NBIS_MINUTIAE 1L
#ifdef __cplusplus
}
#endif
#endif
