/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jlibfprint_JlibFprint_fp_print_data */

#ifndef _Included_jlibfprint_JlibFprint_fp_print_data
#define _Included_jlibfprint_JlibFprint_fp_print_data
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
