/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jlibfprint_JlibFprint */

#ifndef _Included_jlibfprint_JlibFprint
#define _Included_jlibfprint_JlibFprint
#ifdef __cplusplus
extern "C" {
#endif
    
   

JNIEXPORT jint JNICALL Java_jlibfprint_DiscoveredDevice_getType
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
