/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jlibfprint_JlibFprint */

#ifndef _Included_jlibfprint_JlibFprint
#define _Included_jlibfprint_JlibFprint
#ifdef __cplusplus
extern "C" {
#endif
#undef jlibfprint_JlibFprint_BOZORTH_THRESHOLD
#define jlibfprint_JlibFprint_BOZORTH_THRESHOLD 40L
/*
 * Class:     jlibfprint_JlibFprint
 * Method:    enroll_finger
 * Signature: ()Ljlibfprint/JlibFprint/fp_print_data;
 */
JNIEXPORT jobject JNICALL Java_jlibfprint_JlibFprint_enroll_1finger
  (JNIEnv *, jobject);

/*
 * Class:     jlibfprint_JlibFprint
 * Method:    img_compare_print_data
 * Signature: (Ljlibfprint/JlibFprint/fp_print_data;Ljlibfprint/JlibFprint/fp_print_data;)I
 */
JNIEXPORT jint JNICALL Java_jlibfprint_JlibFprint_img_1compare_1print_1data
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
