/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jlibfprint_JlibFprint_EnrollException */

#ifndef _Included_jlibfprint_JlibFprint_EnrollException
#define _Included_jlibfprint_JlibFprint_EnrollException
#ifdef __cplusplus
extern "C" {
#endif
#undef jlibfprint_JlibFprint_EnrollException_serialVersionUID
#define jlibfprint_JlibFprint_EnrollException_serialVersionUID -3042686055658047285LL
#undef jlibfprint_JlibFprint_EnrollException_serialVersionUID
#define jlibfprint_JlibFprint_EnrollException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
